import Head from 'next/head';

import Layout from '../components/Layout';
import Header from '../components/Header';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Responsive Menu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Layout></Layout>
    </div>
  );
}
